### ISSUE TITLE
Clean up of html and ui. lol no offense rourke

### ISSUE THREAD

**Issue by kcox40** [MissionSupport/MissionSupportDemo#40]

**Comment by rourke750** [comment]
My ui that i create is for usability not because it looks good.  None taken.

**Comment by pace543** [comment]
Working on sidebar profile edit UI.

**Comment by kcox40** [comment]
@pace543 sorry... basically already did the sidebar profile edit/view... havent pushed yet

**Comment by kcox40** [comment]
ill push to katieStuff
