### ISSUE TITLE
Side Bar issues

### ISSUE THREAD

**Issue by rourke750** [MissionSupport/MissionSupportDemo#41]
Some things I've noticed.

1. Cog is visible on log in page.

2. After clicking on a settings option there is no visible way to go back to the main settings page.

3. Messing with the url and resetting it to /landing makes the setting bar empty.

Otherwise looks good!

**Comment by kcox40** [comment]
@rourke750 plz review

**Comment by rourke750** [comment]
Perfect seems fixed.  Only other thing it there is now a back button on main settings page.

New bug though when going to a site and then refreshing the cog disappears.

**Comment by rourke750** [comment]
Opening console or shrinking page squishes cog.

**Comment by rourke750** [comment]
After pressing upload button it should reset and allow you to upload a different file.  Should account for a file still in progress of uploading.
