### ISSUE TITLE
Create User profile

### ISSUE THREAD

**Issue by rourke750** [MissionSupport/MissionSupportDemo#7]
- [ ] Create profile and allow users to modify information
- [ ] Allow users to view their profile and information

**Comment by rourke750** [comment]
Currently working on auto generating certain database actions like user_preferences where its important that it gets generated but we dont want the client to do it.

**Comment by kcox40** [comment]
@rourke750 Is any of the other information used when registering (org, first name, last, name...) currently being stored in firebase?

**Comment by kcox40** [comment]
@rourke750 nevermind just checked it is uploading to firebase. What other information should be view-able on this page?
-Username
-Email
-First Name
-LastName
-Org
-IsAdmin(?)
-preferences(?)
    -like fav regions and checklist pref?
-doctor type /title(?)

Also is this a separate page for viewing or is this all contained within the sidebar? Or is it sidebar with option of full page view

**Comment by kcox40** [comment]
-enable auto media upload? (note to self)

**Comment by kcox40** [comment]
-View 'My media'? (note to self ideasss)

**Comment by rourke750** [comment]
So for profile I was thinking that for database stuff that the user can control would be put in the users collection.  Stuff in the users_preferences would be stuff that the user has no control over to change but can view.  So we can show both or select stuff but the stuff in user_preferences will not be modifiable by the user.
